// Code generated by the Encore 1.48.8 client generator. DO NOT EDIT.

// Disable eslint, jshint, and jslint for this file.
/* eslint-disable */
/* jshint ignore:start */
/*jslint-disable*/
import type { CookieWithOptions } from "encore.dev/api";

/**
 * BaseURL is the base URL for calling the Encore application's API.
 */
export type BaseURL = string

export const Local: BaseURL = "http://localhost:4000"

/**
 * Environment returns a BaseURL for calling the cloud environment with the given name.
 */
export function Environment(name: string): BaseURL {
    return `https://${name}-.encr.app`
}

/**
 * PreviewEnv returns a BaseURL for calling the preview environment with the given PR number.
 */
export function PreviewEnv(pr: number | string): BaseURL {
    return Environment(`pr${pr}`)
}

const BROWSER = typeof globalThis === "object" && ("window" in globalThis);

/**
 * Client is an API client for the  Encore application.
 */
export class Client {
    public readonly admin: admin.ServiceClient
    public readonly listing: listing.ServiceClient
    public readonly referral: referral.ServiceClient
    public readonly user: user.ServiceClient
    public readonly wanted: wanted.ServiceClient
    private readonly options: ClientOptions
    private readonly target: string


    /**
     * Creates a Client for calling the public and authenticated APIs of your Encore application.
     *
     * @param target  The target which the client should be configured to use. See Local and Environment for options.
     * @param options Options for the client
     */
    constructor(target: BaseURL, options?: ClientOptions) {
        this.target = target
        this.options = options ?? {}
        const base = new BaseClient(this.target, this.options)
        this.admin = new admin.ServiceClient(base)
        this.listing = new listing.ServiceClient(base)
        this.referral = new referral.ServiceClient(base)
        this.user = new user.ServiceClient(base)
        this.wanted = new wanted.ServiceClient(base)
    }

    /**
     * Creates a new Encore client with the given client options set.
     *
     * @param options Client options to set. They are merged with existing options.
     **/
    public with(options: ClientOptions): Client {
        return new Client(this.target, {
            ...this.options,
            ...options,
        })
    }
}

/**
 * ClientOptions allows you to override any default behaviour within the generated Encore client.
 */
export interface ClientOptions {
    /**
     * By default the client will use the inbuilt fetch function for making the API requests.
     * however you can override it with your own implementation here if you want to run custom
     * code on each API request made or response received.
     */
    fetcher?: Fetcher

    /** Default RequestInit to be used for the client */
    requestInit?: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { getAnalytics as api_admin_get_analytics_getAnalytics } from "~backend/admin/get_analytics";
import { moderateListing as api_admin_moderate_listing_moderateListing } from "~backend/admin/moderate_listing";

export namespace admin {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.getAnalytics = this.getAnalytics.bind(this)
            this.moderateListing = this.moderateListing.bind(this)
        }

        /**
         * Retrieves comprehensive analytics for admin dashboard.
         */
        public async getAnalytics(): Promise<ResponseType<typeof api_admin_get_analytics_getAnalytics>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/admin/analytics`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_admin_get_analytics_getAnalytics>
        }

        /**
         * Moderates a listing (approve, reject, or flag).
         */
        public async moderateListing(params: RequestType<typeof api_admin_moderate_listing_moderateListing>): Promise<void> {
            await this.baseClient.callTypedAPI(`/admin/moderate`, {method: "POST", body: JSON.stringify(params)})
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createListing as api_listing_create_listing_createListing } from "~backend/listing/create_listing";
import { createShop as api_listing_create_shop_createShop } from "~backend/listing/create_shop";
import { deleteListing as api_listing_delete_listing_deleteListing } from "~backend/listing/delete_listing";
import { getListing as api_listing_get_listing_getListing } from "~backend/listing/get_listing";
import { listCategories as api_listing_list_categories_listCategories } from "~backend/listing/list_categories";
import { listGalleries as api_listing_list_galleries_listGalleries } from "~backend/listing/list_galleries";
import { listListings as api_listing_list_listings_listListings } from "~backend/listing/list_listings";
import { listShops as api_listing_list_shops_listShops } from "~backend/listing/list_shops";
import { updateListing as api_listing_update_listing_updateListing } from "~backend/listing/update_listing";

export namespace listing {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createListing = this.createListing.bind(this)
            this.createShop = this.createShop.bind(this)
            this.deleteListing = this.deleteListing.bind(this)
            this.getListing = this.getListing.bind(this)
            this.listCategories = this.listCategories.bind(this)
            this.listGalleries = this.listGalleries.bind(this)
            this.listListings = this.listListings.bind(this)
            this.listShops = this.listShops.bind(this)
            this.updateListing = this.updateListing.bind(this)
        }

        /**
         * Creates a new listing.
         */
        public async createListing(params: RequestType<typeof api_listing_create_listing_createListing>): Promise<ResponseType<typeof api_listing_create_listing_createListing>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/listings`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_listing_create_listing_createListing>
        }

        /**
         * Creates a new shop in a gallery.
         */
        public async createShop(params: RequestType<typeof api_listing_create_shop_createShop>): Promise<ResponseType<typeof api_listing_create_shop_createShop>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shops`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_listing_create_shop_createShop>
        }

        /**
         * Deletes a listing.
         */
        public async deleteListing(params: { id: number }): Promise<void> {
            await this.baseClient.callTypedAPI(`/listings/${encodeURIComponent(params.id)}`, {method: "DELETE", body: undefined})
        }

        /**
         * Retrieves a single listing with full details.
         */
        public async getListing(params: { id: number }): Promise<ResponseType<typeof api_listing_get_listing_getListing>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/listings/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_listing_get_listing_getListing>
        }

        /**
         * Retrieves all available categories.
         */
        public async listCategories(): Promise<ResponseType<typeof api_listing_list_categories_listCategories>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/categories`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_listing_list_categories_listCategories>
        }

        /**
         * Retrieves all galleries with their zones and locations.
         */
        public async listGalleries(): Promise<ResponseType<typeof api_listing_list_galleries_listGalleries>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/galleries`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_listing_list_galleries_listGalleries>
        }

        /**
         * Retrieves listings with filtering and search capabilities.
         */
        public async listListings(params: RequestType<typeof api_listing_list_listings_listListings>): Promise<ResponseType<typeof api_listing_list_listings_listListings>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "category_id":  params["category_id"] === undefined ? undefined : String(params["category_id"]),
                "gallery_id":   params["gallery_id"] === undefined ? undefined : String(params["gallery_id"]),
                limit:          params.limit === undefined ? undefined : String(params.limit),
                "listing_type": params["listing_type"] === undefined ? undefined : String(params["listing_type"]),
                offset:         params.offset === undefined ? undefined : String(params.offset),
                search:         params.search,
                "shop_id":      params["shop_id"] === undefined ? undefined : String(params["shop_id"]),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/listings`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_listing_list_listings_listListings>
        }

        /**
         * Retrieves shops, optionally filtered by gallery.
         */
        public async listShops(params: RequestType<typeof api_listing_list_shops_listShops>): Promise<ResponseType<typeof api_listing_list_shops_listShops>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "gallery_id": params["gallery_id"] === undefined ? undefined : String(params["gallery_id"]),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/shops`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_listing_list_shops_listShops>
        }

        /**
         * Updates an existing listing.
         */
        public async updateListing(params: RequestType<typeof api_listing_update_listing_updateListing>): Promise<ResponseType<typeof api_listing_update_listing_updateListing>> {
            // Construct the body with only the fields which we want encoded within the body (excluding query string or header fields)
            const body: Record<string, any> = {
                "category_id": params["category_id"],
                currency:      params.currency,
                description:   params.description,
                images:        params.images,
                "is_active":   params["is_active"],
                price:         params.price,
                title:         params.title,
            }

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/listings/${encodeURIComponent(params.id)}`, {method: "PUT", body: JSON.stringify(body)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_listing_update_listing_updateListing>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { confirmSale as api_referral_confirm_sale_confirmSale } from "~backend/referral/confirm_sale";
import { createReferral as api_referral_create_referral_createReferral } from "~backend/referral/create_referral";
import { listReferrals as api_referral_list_referrals_listReferrals } from "~backend/referral/list_referrals";
import { trackClick as api_referral_track_click_trackClick } from "~backend/referral/track_click";

export namespace referral {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.confirmSale = this.confirmSale.bind(this)
            this.createReferral = this.createReferral.bind(this)
            this.listReferrals = this.listReferrals.bind(this)
            this.trackClick = this.trackClick.bind(this)
        }

        /**
         * Confirms a sale and processes referral gifts points.
         */
        public async confirmSale(params: RequestType<typeof api_referral_confirm_sale_confirmSale>): Promise<ResponseType<typeof api_referral_confirm_sale_confirmSale>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/sales/confirm`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_referral_confirm_sale_confirmSale>
        }

        /**
         * Creates a new referral link for sharing a listing.
         */
        public async createReferral(params: RequestType<typeof api_referral_create_referral_createReferral>): Promise<ResponseType<typeof api_referral_create_referral_createReferral>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/referrals`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_referral_create_referral_createReferral>
        }

        /**
         * Retrieves referrals for a specific sharer.
         */
        public async listReferrals(params: RequestType<typeof api_referral_list_referrals_listReferrals>): Promise<ResponseType<typeof api_referral_list_referrals_listReferrals>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "sharer_phone": params["sharer_phone"],
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/referrals`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_referral_list_referrals_listReferrals>
        }

        /**
         * Tracks a click on a referral link.
         */
        public async trackClick(params: RequestType<typeof api_referral_track_click_trackClick>): Promise<void> {
            await this.baseClient.callTypedAPI(`/referrals/track`, {method: "POST", body: JSON.stringify(params)})
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createUser as api_user_create_user_createUser } from "~backend/user/create_user";
import { getUser as api_user_get_user_getUser } from "~backend/user/get_user";
import { getUserByPhone as api_user_get_user_by_phone_getUserByPhone } from "~backend/user/get_user_by_phone";
import { listUsers as api_user_list_users_listUsers } from "~backend/user/list_users";
import { updateGiftsPoints as api_user_update_gifts_points_updateGiftsPoints } from "~backend/user/update_gifts_points";
import { updateTrustScore as api_user_update_trust_score_updateTrustScore } from "~backend/user/update_trust_score";

export namespace user {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createUser = this.createUser.bind(this)
            this.getUser = this.getUser.bind(this)
            this.getUserByPhone = this.getUserByPhone.bind(this)
            this.listUsers = this.listUsers.bind(this)
            this.updateGiftsPoints = this.updateGiftsPoints.bind(this)
            this.updateTrustScore = this.updateTrustScore.bind(this)
        }

        /**
         * Creates a new user.
         */
        public async createUser(params: RequestType<typeof api_user_create_user_createUser>): Promise<ResponseType<typeof api_user_create_user_createUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_create_user_createUser>
        }

        /**
         * Retrieves a single user by ID.
         */
        public async getUser(params: { id: number }): Promise<ResponseType<typeof api_user_get_user_getUser>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/${encodeURIComponent(params.id)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_get_user_getUser>
        }

        /**
         * Retrieves a user by phone number.
         */
        public async getUserByPhone(params: { phone: string }): Promise<ResponseType<typeof api_user_get_user_by_phone_getUserByPhone>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/phone/${encodeURIComponent(params.phone)}`, {method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_get_user_by_phone_getUserByPhone>
        }

        /**
         * Retrieves users with optional filtering by type.
         */
        public async listUsers(params: RequestType<typeof api_user_list_users_listUsers>): Promise<ResponseType<typeof api_user_list_users_listUsers>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                limit:       params.limit === undefined ? undefined : String(params.limit),
                offset:      params.offset === undefined ? undefined : String(params.offset),
                "user_type": params["user_type"] === undefined ? undefined : String(params["user_type"]),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_list_users_listUsers>
        }

        /**
         * Updates a user's gifts points balance.
         */
        public async updateGiftsPoints(params: RequestType<typeof api_user_update_gifts_points_updateGiftsPoints>): Promise<ResponseType<typeof api_user_update_gifts_points_updateGiftsPoints>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/gifts-points`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_update_gifts_points_updateGiftsPoints>
        }

        /**
         * Updates a user's trust score.
         */
        public async updateTrustScore(params: RequestType<typeof api_user_update_trust_score_updateTrustScore>): Promise<ResponseType<typeof api_user_update_trust_score_updateTrustScore>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/users/trust-score`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_user_update_trust_score_updateTrustScore>
        }
    }
}

/**
 * Import the endpoint handlers to derive the types for the client.
 */
import { createMatch as api_wanted_create_match_createMatch } from "~backend/wanted/create_match";
import { listMatches as api_wanted_list_matches_listMatches } from "~backend/wanted/list_matches";
import { revealContact as api_wanted_reveal_contact_revealContact } from "~backend/wanted/reveal_contact";

export namespace wanted {

    export class ServiceClient {
        private baseClient: BaseClient

        constructor(baseClient: BaseClient) {
            this.baseClient = baseClient
            this.createMatch = this.createMatch.bind(this)
            this.listMatches = this.listMatches.bind(this)
            this.revealContact = this.revealContact.bind(this)
        }

        /**
         * Creates a match between a wanted listing and an offering.
         */
        public async createMatch(params: RequestType<typeof api_wanted_create_match_createMatch>): Promise<ResponseType<typeof api_wanted_create_match_createMatch>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/wanted/matches`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_wanted_create_match_createMatch>
        }

        /**
         * Retrieves matches for buyers or vendors.
         */
        public async listMatches(params: RequestType<typeof api_wanted_list_matches_listMatches>): Promise<ResponseType<typeof api_wanted_list_matches_listMatches>> {
            // Convert our params into the objects we need for the request
            const query = makeRecord<string, string | string[]>({
                "buyer_id":  params["buyer_id"] === undefined ? undefined : String(params["buyer_id"]),
                "vendor_id": params["vendor_id"] === undefined ? undefined : String(params["vendor_id"]),
            })

            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/wanted/matches`, {query, method: "GET", body: undefined})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_wanted_list_matches_listMatches>
        }

        /**
         * Reveals vendor contact information after payment.
         */
        public async revealContact(params: RequestType<typeof api_wanted_reveal_contact_revealContact>): Promise<ResponseType<typeof api_wanted_reveal_contact_revealContact>> {
            // Now make the actual call to the API
            const resp = await this.baseClient.callTypedAPI(`/wanted/reveal-contact`, {method: "POST", body: JSON.stringify(params)})
            return JSON.parse(await resp.text(), dateReviver) as ResponseType<typeof api_wanted_reveal_contact_revealContact>
        }
    }
}


type PickMethods<Type> = Omit<CallParameters, "method"> & { method?: Type };

// Helper type to omit all fields that are cookies.
type OmitCookie<T> = {
  [K in keyof T as T[K] extends CookieWithOptions<any> ? never : K]: T[K];
};

type RequestType<Type extends (...args: any[]) => any> =
  Parameters<Type> extends [infer H, ...any[]]
    ? OmitCookie<H>
    : void;

type ResponseType<Type extends (...args: any[]) => any> = OmitCookie<Awaited<ReturnType<Type>>>;

function dateReviver(key: string, value: any): any {
  if (
    typeof value === "string" &&
    value.length >= 10 &&
    value.charCodeAt(0) >= 48 && // '0'
    value.charCodeAt(0) <= 57 // '9'
  ) {
    const parsedDate = new Date(value);
    if (!isNaN(parsedDate.getTime())) {
      return parsedDate;
    }
  }
  return value;
}


function encodeQuery(parts: Record<string, string | string[]>): string {
    const pairs: string[] = []
    for (const key in parts) {
        const val = (Array.isArray(parts[key]) ?  parts[key] : [parts[key]]) as string[]
        for (const v of val) {
            pairs.push(`${key}=${encodeURIComponent(v)}`)
        }
    }
    return pairs.join("&")
}

// makeRecord takes a record and strips any undefined values from it,
// and returns the same record with a narrower type.
// @ts-ignore - TS ignore because makeRecord is not always used
function makeRecord<K extends string | number | symbol, V>(record: Record<K, V | undefined>): Record<K, V> {
    for (const key in record) {
        if (record[key] === undefined) {
            delete record[key]
        }
    }
    return record as Record<K, V>
}

import {
  StreamInOutHandlerFn,
  StreamInHandlerFn,
  StreamOutHandlerFn,
} from "encore.dev/api";

type StreamRequest<Type> = Type extends
  | StreamInOutHandlerFn<any, infer Req, any>
  | StreamInHandlerFn<any, infer Req, any>
  | StreamOutHandlerFn<any, any>
  ? Req
  : never;

type StreamResponse<Type> = Type extends
  | StreamInOutHandlerFn<any, any, infer Resp>
  | StreamInHandlerFn<any, any, infer Resp>
  | StreamOutHandlerFn<any, infer Resp>
  ? Resp
  : never;


function encodeWebSocketHeaders(headers: Record<string, string>) {
    // url safe, no pad
    const base64encoded = btoa(JSON.stringify(headers))
      .replaceAll("=", "")
      .replaceAll("+", "-")
      .replaceAll("/", "_");
    return "encore.dev.headers." + base64encoded;
}

class WebSocketConnection {
    public ws: WebSocket;

    private hasUpdateHandlers: (() => void)[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        let protocols = ["encore-ws"];
        if (headers) {
            protocols.push(encodeWebSocketHeaders(headers))
        }

        this.ws = new WebSocket(url, protocols)

        this.on("error", () => {
            this.resolveHasUpdateHandlers();
        });

        this.on("close", () => {
            this.resolveHasUpdateHandlers();
        });
    }

    resolveHasUpdateHandlers() {
        const handlers = this.hasUpdateHandlers;
        this.hasUpdateHandlers = [];

        for (const handler of handlers) {
            handler()
        }
    }

    async hasUpdate() {
        // await until a new message have been received, or the socket is closed
        await new Promise((resolve) => {
            this.hasUpdateHandlers.push(() => resolve(null))
        });
    }

    on(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.addEventListener(type, handler);
    }

    off(type: "error" | "close" | "message" | "open", handler: (event: any) => void) {
        this.ws.removeEventListener(type, handler);
    }

    close() {
        this.ws.close();
    }
}

export class StreamInOut<Request, Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamIn<Response> {
    public socket: WebSocketConnection;
    private buffer: Response[] = [];

    constructor(url: string, headers?: Record<string, string>) {
        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            this.buffer.push(JSON.parse(event.data, dateReviver));
            this.socket.resolveHasUpdateHandlers();
        });
    }

    close() {
        this.socket.close();
    }

    async next(): Promise<Response | undefined> {
        for await (const next of this) return next;
        return undefined;
    }

    async *[Symbol.asyncIterator](): AsyncGenerator<Response, undefined, void> {
        while (true) {
            if (this.buffer.length > 0) {
                yield this.buffer.shift() as Response;
            } else {
                if (this.socket.ws.readyState === WebSocket.CLOSED) return;
                await this.socket.hasUpdate();
            }
        }
    }
}

export class StreamOut<Request, Response> {
    public socket: WebSocketConnection;
    private responseValue: Promise<Response>;

    constructor(url: string, headers?: Record<string, string>) {
        let responseResolver: (_: any) => void;
        this.responseValue = new Promise((resolve) => responseResolver = resolve);

        this.socket = new WebSocketConnection(url, headers);
        this.socket.on("message", (event: any) => {
            responseResolver(JSON.parse(event.data, dateReviver))
        });
    }

    async response(): Promise<Response> {
        return this.responseValue;
    }

    close() {
        this.socket.close();
    }

    async send(msg: Request) {
        if (this.socket.ws.readyState === WebSocket.CONNECTING) {
            // await that the socket is opened
            await new Promise((resolve) => {
                this.socket.ws.addEventListener("open", resolve, { once: true });
            });
        }

        return this.socket.ws.send(JSON.stringify(msg));
    }
}
// CallParameters is the type of the parameters to a method call, but require headers to be a Record type
type CallParameters = Omit<RequestInit, "headers"> & {
    /** Headers to be sent with the request */
    headers?: Record<string, string>

    /** Query parameters to be sent with the request */
    query?: Record<string, string | string[]>
}


// A fetcher is the prototype for the inbuilt Fetch function
export type Fetcher = typeof fetch;

const boundFetch = fetch.bind(this);

class BaseClient {
    readonly baseURL: string
    readonly fetcher: Fetcher
    readonly headers: Record<string, string>
    readonly requestInit: Omit<RequestInit, "headers"> & { headers?: Record<string, string> }

    constructor(baseURL: string, options: ClientOptions) {
        this.baseURL = baseURL
        this.headers = {}

        // Add User-Agent header if the script is running in the server
        // because browsers do not allow setting User-Agent headers to requests
        if (!BROWSER) {
            this.headers["User-Agent"] = "-Generated-TS-Client (Encore/1.48.8)";
        }

        this.requestInit = options.requestInit ?? {};

        // Setup what fetch function we'll be using in the base client
        if (options.fetcher !== undefined) {
            this.fetcher = options.fetcher
        } else {
            this.fetcher = boundFetch
        }
    }

    async getAuthData(): Promise<CallParameters | undefined> {
        return undefined;
    }

    // createStreamInOut sets up a stream to a streaming API endpoint.
    async createStreamInOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamInOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamInOut(this.baseURL + path + queryString, headers);
    }

    // createStreamIn sets up a stream to a streaming API endpoint.
    async createStreamIn<Response>(path: string, params?: CallParameters): Promise<StreamIn<Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamIn(this.baseURL + path + queryString, headers);
    }

    // createStreamOut sets up a stream to a streaming API endpoint.
    async createStreamOut<Request, Response>(path: string, params?: CallParameters): Promise<StreamOut<Request, Response>> {
        let { query, headers } = params ?? {};

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                headers = {...headers, ...authData.headers};
            }
        }

        const queryString = query ? '?' + encodeQuery(query) : ''
        return new StreamOut(this.baseURL + path + queryString, headers);
    }

    // callTypedAPI makes an API call, defaulting content type to "application/json"
    public async callTypedAPI(path: string, params?: CallParameters): Promise<Response> {
        return this.callAPI(path, {
            ...params,
            headers: { "Content-Type": "application/json", ...params?.headers }
        });
    }

    // callAPI is used by each generated API method to actually make the request
    public async callAPI(path: string, params?: CallParameters): Promise<Response> {
        let { query, headers, ...rest } = params ?? {}
        const init = {
            ...this.requestInit,
            ...rest,
        }

        // Merge our headers with any predefined headers
        init.headers = {...this.headers, ...init.headers, ...headers}

        // Fetch auth data if there is any
        const authData = await this.getAuthData();

        // If we now have authentication data, add it to the request
        if (authData) {
            if (authData.query) {
                query = {...query, ...authData.query};
            }
            if (authData.headers) {
                init.headers = {...init.headers, ...authData.headers};
            }
        }

        // Make the actual request
        const queryString = query ? '?' + encodeQuery(query) : ''
        const response = await this.fetcher(this.baseURL+path+queryString, init)

        // handle any error responses
        if (!response.ok) {
            // try and get the error message from the response body
            let body: APIErrorResponse = { code: ErrCode.Unknown, message: `request failed: status ${response.status}` }

            // if we can get the structured error we should, otherwise give a best effort
            try {
                const text = await response.text()

                try {
                    const jsonBody = JSON.parse(text)
                    if (isAPIErrorResponse(jsonBody)) {
                        body = jsonBody
                    } else {
                        body.message += ": " + JSON.stringify(jsonBody)
                    }
                } catch {
                    body.message += ": " + text
                }
            } catch (e) {
                // otherwise we just append the text to the error message
                body.message += ": " + String(e)
            }

            throw new APIError(response.status, body)
        }

        return response
    }
}

/**
 * APIErrorDetails represents the response from an Encore API in the case of an error
 */
interface APIErrorResponse {
    code: ErrCode
    message: string
    details?: any
}

function isAPIErrorResponse(err: any): err is APIErrorResponse {
    return (
        err !== undefined && err !== null &&
        isErrCode(err.code) &&
        typeof(err.message) === "string" &&
        (err.details === undefined || err.details === null || typeof(err.details) === "object")
    )
}

function isErrCode(code: any): code is ErrCode {
    return code !== undefined && Object.values(ErrCode).includes(code)
}

/**
 * APIError represents a structured error as returned from an Encore application.
 */
export class APIError extends Error {
    /**
     * The HTTP status code associated with the error.
     */
    public readonly status: number

    /**
     * The Encore error code
     */
    public readonly code: ErrCode

    /**
     * The error details
     */
    public readonly details?: any

    constructor(status: number, response: APIErrorResponse) {
        // extending errors causes issues after you construct them, unless you apply the following fixes
        super(response.message);

        // set error name as constructor name, make it not enumerable to keep native Error behavior
        // https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target#new.target_in_constructors
        Object.defineProperty(this, 'name', {
            value:        'APIError',
            enumerable:   false,
            configurable: true,
        })

        // fix the prototype chain
        if ((Object as any).setPrototypeOf == undefined) {
            (this as any).__proto__ = APIError.prototype
        } else {
            Object.setPrototypeOf(this, APIError.prototype);
        }

        // capture a stack trace
        if ((Error as any).captureStackTrace !== undefined) {
            (Error as any).captureStackTrace(this, this.constructor);
        }

        this.status = status
        this.code = response.code
        this.details = response.details
    }
}

/**
 * Typeguard allowing use of an APIError's fields'
 */
export function isAPIError(err: any): err is APIError {
    return err instanceof APIError;
}

export enum ErrCode {
    /**
     * OK indicates the operation was successful.
     */
    OK = "ok",

    /**
     * Canceled indicates the operation was canceled (typically by the caller).
     *
     * Encore will generate this error code when cancellation is requested.
     */
    Canceled = "canceled",

    /**
     * Unknown error. An example of where this error may be returned is
     * if a Status value received from another address space belongs to
     * an error-space that is not known in this address space. Also
     * errors raised by APIs that do not return enough error information
     * may be converted to this error.
     *
     * Encore will generate this error code in the above two mentioned cases.
     */
    Unknown = "unknown",

    /**
     * InvalidArgument indicates client specified an invalid argument.
     * Note that this differs from FailedPrecondition. It indicates arguments
     * that are problematic regardless of the state of the system
     * (e.g., a malformed file name).
     *
     * This error code will not be generated by the gRPC framework.
     */
    InvalidArgument = "invalid_argument",

    /**
     * DeadlineExceeded means operation expired before completion.
     * For operations that change the state of the system, this error may be
     * returned even if the operation has completed successfully. For
     * example, a successful response from a server could have been delayed
     * long enough for the deadline to expire.
     *
     * The gRPC framework will generate this error code when the deadline is
     * exceeded.
     */
    DeadlineExceeded = "deadline_exceeded",

    /**
     * NotFound means some requested entity (e.g., file or directory) was
     * not found.
     *
     * This error code will not be generated by the gRPC framework.
     */
    NotFound = "not_found",

    /**
     * AlreadyExists means an attempt to create an entity failed because one
     * already exists.
     *
     * This error code will not be generated by the gRPC framework.
     */
    AlreadyExists = "already_exists",

    /**
     * PermissionDenied indicates the caller does not have permission to
     * execute the specified operation. It must not be used for rejections
     * caused by exhausting some resource (use ResourceExhausted
     * instead for those errors). It must not be
     * used if the caller cannot be identified (use Unauthenticated
     * instead for those errors).
     *
     * This error code will not be generated by the gRPC core framework,
     * but expect authentication middleware to use it.
     */
    PermissionDenied = "permission_denied",

    /**
     * ResourceExhausted indicates some resource has been exhausted, perhaps
     * a per-user quota, or perhaps the entire file system is out of space.
     *
     * This error code will be generated by the gRPC framework in
     * out-of-memory and server overload situations, or when a message is
     * larger than the configured maximum size.
     */
    ResourceExhausted = "resource_exhausted",

    /**
     * FailedPrecondition indicates operation was rejected because the
     * system is not in a state required for the operation's execution.
     * For example, directory to be deleted may be non-empty, an rmdir
     * operation is applied to a non-directory, etc.
     *
     * A litmus test that may help a service implementor in deciding
     * between FailedPrecondition, Aborted, and Unavailable:
     *  (a) Use Unavailable if the client can retry just the failing call.
     *  (b) Use Aborted if the client should retry at a higher-level
     *      (e.g., restarting a read-modify-write sequence).
     *  (c) Use FailedPrecondition if the client should not retry until
     *      the system state has been explicitly fixed. E.g., if an "rmdir"
     *      fails because the directory is non-empty, FailedPrecondition
     *      should be returned since the client should not retry unless
     *      they have first fixed up the directory by deleting files from it.
     *  (d) Use FailedPrecondition if the client performs conditional
     *      REST Get/Update/Delete on a resource and the resource on the
     *      server does not match the condition. E.g., conflicting
     *      read-modify-write on the same resource.
     *
     * This error code will not be generated by the gRPC framework.
     */
    FailedPrecondition = "failed_precondition",

    /**
     * Aborted indicates the operation was aborted, typically due to a
     * concurrency issue like sequencer check failures, transaction aborts,
     * etc.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     */
    Aborted = "aborted",

    /**
     * OutOfRange means operation was attempted past the valid range.
     * E.g., seeking or reading past end of file.
     *
     * Unlike InvalidArgument, this error indicates a problem that may
     * be fixed if the system state changes. For example, a 32-bit file
     * system will generate InvalidArgument if asked to read at an
     * offset that is not in the range [0,2^32-1], but it will generate
     * OutOfRange if asked to read from an offset past the current
     * file size.
     *
     * There is a fair bit of overlap between FailedPrecondition and
     * OutOfRange. We recommend using OutOfRange (the more specific
     * error) when it applies so that callers who are iterating through
     * a space can easily look for an OutOfRange error to detect when
     * they are done.
     *
     * This error code will not be generated by the gRPC framework.
     */
    OutOfRange = "out_of_range",

    /**
     * Unimplemented indicates operation is not implemented or not
     * supported/enabled in this service.
     *
     * This error code will be generated by the gRPC framework. Most
     * commonly, you will see this error code when a method implementation
     * is missing on the server. It can also be generated for unknown
     * compression algorithms or a disagreement as to whether an RPC should
     * be streaming.
     */
    Unimplemented = "unimplemented",

    /**
     * Internal errors. Means some invariants expected by underlying
     * system has been broken. If you see one of these errors,
     * something is very broken.
     *
     * This error code will be generated by the gRPC framework in several
     * internal error conditions.
     */
    Internal = "internal",

    /**
     * Unavailable indicates the service is currently unavailable.
     * This is a most likely a transient condition and may be corrected
     * by retrying with a backoff. Note that it is not always safe to retry
     * non-idempotent operations.
     *
     * See litmus test above for deciding between FailedPrecondition,
     * Aborted, and Unavailable.
     *
     * This error code will be generated by the gRPC framework during
     * abrupt shutdown of a server process or network connection.
     */
    Unavailable = "unavailable",

    /**
     * DataLoss indicates unrecoverable data loss or corruption.
     *
     * This error code will not be generated by the gRPC framework.
     */
    DataLoss = "data_loss",

    /**
     * Unauthenticated indicates the request does not have valid
     * authentication credentials for the operation.
     *
     * The gRPC framework will generate this error code when the
     * authentication metadata is invalid or a Credentials callback fails,
     * but also expect authentication middleware to generate it.
     */
    Unauthenticated = "unauthenticated",
}

export default new Client(import.meta.env.VITE_CLIENT_TARGET, { requestInit: { credentials: "include" } });
